### PR TITLE
add nft bridge examples and marketplace integration doc

### PR DESCRIPTION
**Pull request by souradeep-das**
- adds a NFT bridge to L1 example and tutorial
- adds guide and example scripts for marketplace bridge integration

### CODE REVIEW

**Comment by boyuan-chen** [comment]
Can we remove the build folder? Also, we need to mention that developers have to contact us to add the pairs in the NFT bridges. It will be nice if we can add the script to allow them to directly test on Rinkeby, so they don't have to spend a day  figuring out how to spin up the local stack. The fraud proof window of Rinkeby is 5 mins, so they can exit their NFT from L2 quickly.

**Review by CAPtheorem — APPROVED** [review]

**Comment by CAPtheorem** [comment]
> Can we remove the build folder? Also, we need to mention that developers have to contact us to add the pairs in the NFT bridges. It will be nice if we can add the script to allow them to directly test on Rinkeby, so they don't have to spend a day to figure out how to spin up the local stack. The fraud proof window of Rinkeby is 5 mins, so they can exit their NFT from L2 quickly.

Yes, @souradeep-das please add that

**Comment by souradeep-das** [comment]
sure, reiterating the pair registration part, 
yeah the only reason the dependency on local stack is to have the essence of using your own contracts (because of the registration part), but nice idea, will add an optional quickstart on rinkeby for people, which can work with pre-deployed preset contracts

**Comment by CAPtheorem** [comment]
moved to /bobanetwork

**Pull request closed without merging**
